[project]
name = "calico"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "click>=8.4.1",
    "dataclasses>=0.8",
    "requests>=2.34.2",
    "tomli-w>=1.2.0",
]

[dependency-groups]
dev = [
    "nuitka>=4.1.2",
    "pyinstaller>=6.21.0",
]
